### ISSUE TITLE
Hopefully this gives you something to go on!

### ISSUE THREAD

**Issue by opatey** [AmitavaHazra/MvcMovieSCIM#4]
I've pulled the solution around a bit and added a copy of Microsoft.SCIM from the main repo.

You'll need to move the database from SQLite -> your SqlServer provider.

The interesting classes are in `MvcMovie\Services` folder - this was what I meant by implementing `IProvider` and `IMonitor` for your needs; the `IProvider` I've added here takes the messages from SCIM and writes them into the shared UserDataContext that is also acting as a data source for the HomeController view, so you can see a simple list of provisioned users that have come in via SCIM

**Comment by AmitavaHazra** [comment]
@opatey ,

I will try to move SQL lite to SQL server DB  and will update you.
Can you please tell me what these value are coming from. which value I need to update for issuer and audience ?

 "Scim": {
    "TokenAudience": "**75340b0e-e6d4-4599-a560-906c44085b17**",
    "TokenIssuer": "https://sts.windows.net/**cbb1a5ac-f33b-45fa-9bf5-f37db0fed422**/"

**Comment by opatey** [comment]
They are from this section of the guide - [Handling endpoint authentication](https://docs.microsoft.com/en-us/azure/active-directory/app-provisioning/use-scim-to-provision-users-and-groups#handling-endpoint-authentication).

I meant to copy your tenant ID over the Token Issuer, but missed with my cursor 😆 

the values you need are:
```
"Scim": {
  "TokenAudience": "8adf8e6e-67b2-4cf2-a259-e3dc5476c621",
  "TokenIssuer": "https://sts.windows.net/75340b0e-e6d4-4599-a560-906c44085b17/"
}
```

Token audience is the standard ID for non-gallery applications, the token issuer is specific to your tenant.

**Comment by AmitavaHazra** [comment]
Ok Got it. I managed to run it changing sql lite to local SQL DB.
then I am trying to make use of Azure SQL DB since I am hosting it on app service. Post that I can get into provisioning.

One point again, Can't we test this provisioning using localhost application ? it would be really helpful to test anything quickly?

**Comment by AmitavaHazra** [comment]
@opatey ,

Finally it worked for me after moving to Azure SQL DB and provisioning is working as expected to DB.
Thanks for your excellent support. Though I  have to see how can we test this in postman.

One point again, 
1. Can't we test this provisioning using localhost application ? it would be really helpful to test anything quickly?
2. In order to test app service hosted application in postman what type of authentication I have to pass if there is any scope to do that.

Please explain above two point then we are good to conclude these.

**Comment by opatey** [comment]
No problem - I'm glad you are starting to see things working. I am not actually a contributor to the [reference code](https://github.com/AzureAD/SCIMReferenceCode) project, but it really helped me to get started with SCIM so maybe I will see if they need a hand with any aspects of it 😄 

On you last 2 questions:

  1. I couldn't find any way to do this quickly/cheaply, but it is really the point of the [Postman test collection](https://github.com/AzureAD/SCIMReferenceCode/blob/master/PostmanCollection.json) in the reference project. Did you try running these? They are like integration tests that 'pretend' to be Azure AD to your local development instance.

  2. You would need to make additional changes to get the `/scim/Users` endpoint to trust a second type of token (eg. one that is generated like the reference project's `/scim/Token` endpoint). You could add [another Bearer authentication scheme](https://github.com/AmitavaHazra/MvcMovieSCIM/blob/159a161c9af79fb96e88de0369a7349fe270d7c2/MvcMovie/Startup.cs#L44) for this and modify the [Users authorization attribute](https://github.com/AmitavaHazra/MvcMovieSCIM/blob/159a161c9af79fb96e88de0369a7349fe270d7c2/Microsoft.SystemForCrossDomainIdentityManagement/Service/Controllers/UsersController.cs#L11) to trust this scheme as well. Just make sure that only you, or people you trust can generate valid bearer tokens. For example, you could generate and show the token on a web page that is only accessible once you have authenticated with Azure AD, like the `HomeController`

**Comment by AmitavaHazra** [comment]
Hello @opatey ,

I could not understand one thing.

_You could add another Bearer authentication scheme for this and modify the Users authorization attribute to trust this scheme as well._

- For this I can do create another authorization policy just like existing with different name.

.AddJwtBearer("scim", options =>
                {
                    options.Authority = Configuration["Scim:TokenIssuer"];
                    options.Audience = Configuration["Scim:TokenAudience"];
                });
But how to do  additional changes to get the /scim/Users endpoint to trust a second type of token?
Also why can't current addJwtBearer token be able to issue token to azure hosted app.

It might be silly question but I need to your help for sure.

**Comment by opatey** [comment]
The [Authentication Schemes](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1#selecting-the-scheme-with-the-authorize-attribute) docs will help you to understand this better than I can explain, but with the `[Authorize]` attribute, you can allow multiple different forms of authentication.

> Also why can't current addJwtBearer token be able to issue token to azure hosted app.

AddJwtBearer only configures the _validation_ side of token authentication - you cannot use the issuer and audience to generate trusted tokens yourself.

But you could call AddJwtBearer _again_ and configure another authentication scheme for tokens that you _can_ generate.

```
.AddJwtBearer("scim", options =>
{
  options.Authority = Configuration["Scim:TokenIssuer"];
  options.Audience = Configuration["Scim:TokenAudience"];
})
.AddJwtBearer("local", options =>
{
  options.TokenValidationParameters =
                        new TokenValidationParameters
                        {
                            ValidIssuer = this.configuration["Local:TokenIssuer"],
                            ValidAudience = this.configuration["Local:TokenAudience"],
                            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(this.configuration["Local:IssuerSigningKey"]))
                        };
});
```

The [UserController's Authorize attribute](https://github.com/AmitavaHazra/MvcMovieSCIM/blob/159a161c9af79fb96e88de0369a7349fe270d7c2/Microsoft.SystemForCrossDomainIdentityManagement/Service/Controllers/UsersController.cs#L11) becomes something like:
```
[Authorize(AuthenticationSchemes = "scim,local")]
```

and then both Microsoft STS tokens and those generated with your local symmetric key `Local:IssuerSigningKey` are trusted.

You can use code similar to the token endpoint in the reference code to generate a trusted token using `Local:IssuerSigningKey`.

**Comment by AmitavaHazra** [comment]
@opatey , I think we can't keep both  .AddJwtBearer in start up file. Can you please change this code in my git hub repository whenever you will have time.
 To generate local issuer signingkey do I need to use certificate ?
Reference:
https://stackoverflow.com/questions/46294373/net-core-issuersigningkey-from-file-for-jwt-bearer-authentication

**Comment by AmitavaHazra** [comment]
@opatey ,

Now I have managed to generate token from localhost and from app service hosted app.
Now api is returning data from localhost address as well as from hosted one.

Also I have added below and got your point. 

Can you just tell me how to can we get this value IssuerSigningKey so that we can make api secure one ?? Time being I have hard coded it.

```
 .AddJwtBearer("scim", options =>
                {
                    options.Authority = Configuration["Scim:TokenIssuer"];
                    options.Audience = Configuration["Scim:TokenAudience"];
                })

                .AddJwtBearer("local", options =>
                {
                    options.TokenValidationParameters =
                                          new TokenValidationParameters
                                          {
                                              ValidIssuer = this.Configuration["Token:TokenIssuer"],
                                              ValidAudience = this.Configuration["Token:TokenAudience"],
                                              IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("A1B2C3D4E5F6A1B2C3D4E5F6"))
                                          };
                })
```

Thanks for your help.

**Comment by opatey** [comment]
Yep - that's right, you could source it from configuration like you have with `Token:TokenIssuer` and `Token:TokenAudience` to move it out of code and into whatever mechanism you are using to deliver secrets to your publicly hosted app.

**Comment by AmitavaHazra** [comment]
@opatey ,

I know how to move it config but just tell me what are the mechanism we can use to generate issuersigninkey ? any reference link ?? just for learning I am asking this info.
